// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(WOVQPOOO[QPO'#CvQaQQOOOiQPO,59bOnQPO'#CwOOQO'#Co'#CoQaQQOOOsQPO'#CyOOQO'#Cq'#CqQdQQOOOxQQO1G.|O}QPO,59cOOQO-E6m-E6mO!SQQO,59eOOQO-E6o-E6oO!bQPO7+$hO!gQPO1G.}OOQO'#Ck'#CkO!lQPO'#CjO!wQSO1G/PO!|QPO1G/PO#RQPO<<HSO#WQQO7+$iO#]QQO,59VO#bQQO'#CrO#mQPO,59UO#bQQO7+$kO#uQSO7+$kOOQOAN=nAN=nO#zQPO'#CxO$PQPO<<HTO$XQPO1G.qO$^QPO,59^OOQO-E6p-E6pO$iQPO<<HVO#bQQO<<HVO$qQPO,59dO#WQQO'#CpO$vQPOAN=oO%OQPOAN=oO%TQQO7+$]OOQOAN=qAN=qO%cQPOAN=qOOQO1G/O1G/OOOQO,59[,59[OOQO-E6n-E6nO%kQPOG23ZO%pQPOG23ZOOQO<<Gw<<GwO%uQPO<<GwOOQOG23]G23]O%zQPOLD(uOOQOLD(uLD(uOOQOAN=cAN=cOOQO!$'La!$'La",
  stateData: "&P~OiOS~OQPO~ORRO~OQSOTVO~OSYO~OWZO~OS]O~OT_O~OS`O~OTaOUcOZaO`aO~OUeO~OXfO~O[hOagOU^X~ObjO~OUkO~OVlO~OTmO~OToO~OTaOZaO`aO~O[hOU^a~ObsO~OYtO~O[uO]wO~OSxO~OagOUfa[fa~OVyOagO~OZ{O~O[uO]!OO~OU!PO~OTaOU!QOZaO`aO~OV!SOagO~OU!TO~OV!UO~OU!VO~OV!WO~O",
  goto: "#PnPPPPPPPPPPPPPPouPPP!S!Y!`!gPPP!m!p!t!zQd]R!RxSb]xQphQrjRzsQUQR[UQvnR}vSXQUR^XQibRqiRQOTTQUQnfR|uVWQUX",
  nodeNames: "⚠ Module Minus KeywordModule LParen Atom RParen Period KeywordExport LBracket Slash Number Comma RBracket ArgList Expr String Colon Arrow",
  maxTerm: 29,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "+x~RdXY!aYZ!a]^!apq!ars!rxy$`yz$e|}$j}!O$o!O!P$|!P!Q%R!Q![%W![!]%`!}#O%e#P#Q%j#T#X%o#X#Y&Q#Y#a%o#a#b(|#b#o%o~!fSi~XY!aYZ!a]^!apq!a~!uVOr!rrs#[s#O!r#O#P#a#P;'S!r;'S;=`$Y<%lO!r~#aO`~~#dRO;'S!r;'S;=`#m;=`O!r~#pWOr!rrs#[s#O!r#O#P#a#P;'S!r;'S;=`$Y;=`<%l!r<%lO!r~$]P;=`<%l!r~$eOS~~$jOU~~$oO[~V$tPQR!`!a$wS$|ObS~%ROV~~%WOY~~%]PZ~!Q![%W~%eOa~~%jOX~~%oO]~Q%tSTQ!Q![%o!c!}%o#R#S%o#T#o%oR&VUTQ!Q![%o!c!}%o#R#S%o#T#l%o#l#m&i#m#o%oR&nUTQ!Q![%o!c!}%o#R#S%o#T#d%o#d#e'Q#e#o%oR'VUTQ!Q![%o!c!}%o#R#S%o#T#c%o#c#d'i#d#o%oR'nUTQ!Q![%o!c!}%o#R#S%o#T#f%o#f#g(Q#g#o%oR(VUTQ!Q![%o!c!}%o#R#S%o#T#h%o#h#i(i#i#o%oR(pSTQWP!Q![%o!c!}%o#R#S%o#T#o%oR)RUTQ!Q![%o!c!}%o#R#S%o#T#c%o#c#d)e#d#o%oR)jUTQ!Q![%o!c!}%o#R#S%o#T#W%o#W#X)|#X#o%oR*RUTQ!Q![%o!c!}%o#R#S%o#T#i%o#i#j*e#j#o%oR*jUTQ!Q![%o!c!}%o#R#S%o#T#`%o#`#a*|#a#o%oR+RUTQ!Q![%o!c!}%o#R#S%o#T#X%o#X#Y+e#Y#o%oR+lSTQRP!Q![%o!c!}%o#R#S%o#T#o%o",
  tokenizers: [0, 1, 2],
  topRules: {"Module":[0,1]},
  tokenPrec: 0
})
